# values.yaml
replicaCount: 3

image:
  repository: 961341535255.dkr.ecr.ap-south-1.amazonaws.com/test  # Replace with your actual image name
  tag: "20241103175014"
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: ecr-secret

service:
  type: NodePort
  port: 5000
  nodePort: 30080  # Optional: fixed NodePort for easy access

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Additional custom values can be added here as needed.
