name: Build and Push Multi-Arch Image to ECR

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        id: ecr-login
        run: |
          echo "Logging in to ECR..."
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com"

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # Specify custom Dockerfile path if needed
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/test:latest
        env:
          DOCKER_BUILDKIT: 1  # Enable BuildKit for multi-arch builds
          
      - name: Verify Image in ECR
        run: |
          echo "Verifying the pushed image in ECR..."
          aws ecr describe-images --repository-name test --region ap-south-1

      - name: Logout from ECR
        run: |
          echo "Logging out from ECR..."
          docker logout "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com"